### ISSUE TITLE
Officeworks delivery

### ISSUE THREAD

**Issue by garner-code** [brainhack-aus/global2022#5]
- [ ] stickers + pens for nametags - TO-GET
- [ ] extension cables + power boards - DEEMED NOT ENOUGH FROM PHOTOS
- [ ] pens and papers - NEED
- [ ] whiteboard markers?

**Comment by tclose** [comment]
Check whether we can deliver to NIF central

**Comment by tclose** [comment]
Address to send it to

Alex Burton, National Imaging Facility
Melbourne Connect Co-Working
Level 2, 700 Swanston St
Carlton VIC 3053
